export interface VerticalConfig {
  id: string;
  label: string;
  description: string;
  categories: string[];
  unitOptions: string[];
  pluralMap: Record<string, string>;
}

export const RETAIL_VERTICALS: Record<string, VerticalConfig> = {
	
grocery: {
  id: "grocery",
  label: "Supermarket & Grocery",
  description: "Household essentials, food items, provisions, personal care products, consumer goods.",
  categories: [
    "Grains, Rice & Cereals",
    "Flour, Baking & Baking Ingredients",
    "Tubers & Root Crops",
    "Fruits & Vegetables",
    "Fresh & Perishable Foods",
    "Meat, Poultry & Protein",
    "Fish & Seafood",
    "Frozen Foods",
    "Dairy, Milk & Eggs",
    "Bread & Bakery Products",
    "Cooking Oil, Fats & Shortening",
    "Seasonings, Spices & Stock Cubes",
    "Salt, Sugar & Sweeteners",
    "Canned & Preserved Foods",
    "Packaged & Processed Foods",
    "Pasta, Noodles & Macaroni",
    "Breakfast Foods & Cereals",
    "Snacks & Confectionery",
    "Biscuits, Crackers & Wafers",
    "Chocolate & Sweets",
    "Beverages",
    "Soft Drinks & Carbonated Drinks",
    "Fruit Juices & Squashes",
    "Malt & Energy Drinks",
    "Tea, Coffee & Cocoa",
    "Bottled & Sachet Water",
    "Alcoholic Beverages",
    "Wine & Spirits",
    "Baby Food & Infant Nutrition",
    "Baby Care Products",
    "Personal Care & Toiletries",
    "Hair Care Products",
    "Oral Care Products",
    "Skin Care & Body Care",
    "Feminine Hygiene",
    "Household Cleaning Products",
    "Laundry & Dishwashing Products",
    "Paper Products & Tissues",
    "Pest Control & Insecticides",
    "Air Fresheners & Fragrances",
    "Kitchen Utensils & Household Items",
    "Food Storage & Containers",
    "Plastic & Disposable Products",
    "Stationery & School Supplies",
    "Toys & Games",
    "Fashion & Personal Accessories",
    "Electronics & Small Gadgets",
    "Batteries & Lighting",
    "Automotive & General Utility Items",
    "Tobacco & Smoking Products",
    "Others"
  ],
  unitOptions: [
    "pc",
    "cup",
    "jar",
    "can",
    "kg",
    "g",
    "litre",
    "ml",
    "pack",
    "packet",
    "carton",
    "crate",
    "bag",
    "tuber",
    "roll",
    "bundle",
    "bottle",
    "sachet",
    "tin",
    "wrap",
    "dozen",
    "tray",
    "case"
  ],
  pluralMap: {
    pc: "Pcs",
    cup: "Cups",
    jar: "Jars",
    can: "Cans",
    kg: "Kg",
    g: "g",
    litre: "Litres",
    ml: "ml",
    pack: "Packs",
    packet: "Packets",
    carton: "Cartons",
    crate: "Crates",
    bag: "Bags",
    tuber: "Tubers",
    roll: "Rolls",
    bundle: "Bundles",
    bottle: "Bottles",
    sachet: "Sachets",
    tin: "Tins",
    wrap: "Wraps",
    dozen: "Dozens",
    tray: "Trays",
    case: "Cases"
  }
},

phones_accessories: {
  id: "phones_accessories",
  label: "Phones & Accessories",
  description: "Mobile gadgets, mobile phones, smartphones, tablets, phone accessories, audio devices.",
  categories: [
    "Smartphones",
    "Feature Phones",
    "Basic & Senior Phones",
    "Tablets & iPads",
    "Refurbished & Used Phones",
    "Phone Cases & Covers",
    "Screen Protectors",
    "Tempered Glass",
    "Phone Pouches & Sleeves",
    "Chargers & Charging Adapters",
    "Fast Chargers",
    "Wireless Chargers",
    "Charging Cables",
    "USB Cables & Adapters",
    "Power Banks",
    "Car Chargers",
    "Wireless & Bluetooth Earbuds",
    "Headphones & Headsets",
    "Bluetooth Speakers",
    "Phone Holders & Stands",
    "Car Phone Mounts",
    "Selfie Sticks & Tripods",
    "Smart Watches & Wearables",
    "Smart Bands",
    "Memory Cards",
    "Card Readers",
    "USB Flash Drives",
    "OTG Adapters",
    "SIM Cards & SIM Accessories",
    "Mobile Broadband & MiFi Devices",
    "Routers & Wi-Fi Devices",
    "Mobile Phone Batteries",
    "Phone Screens & Displays",
    "Phone Housing & Back Covers",
    "Phone Spare Parts",
    "Camera & Lens Accessories",
    "Phone Repair Tools",
    "Phone Repair Consumables",
    "Phone Cleaning & Maintenance",
    "Gaming Accessories",
    "Mobile Gaming Controllers",
    "Power & Protection Accessories",
    "Phone & Tablet Cables",
    "Apple Accessories",
    "Android Accessories",
    "Others"
  ],
  unitOptions: [
    "pc",
    "unit",
    "piece",
    "pair",
    "set",
    "pack",
    "box",
    "carton",
    "bundle",
    "kit",
    "roll",
    "meter",
    "length"
  ],
  pluralMap: {
    pc: "Pcs",
    unit: "Units",
    piece: "Pieces",
    pair: "Pairs",
    set: "Sets",
    pack: "Packs",
    box: "Boxes",
    carton: "Cartons",
    bundle: "Bundles",
    kit: "Kits",
    roll: "Rolls",
    meter: "Meters",
    length: "Lengths"
  }
},

computers_it: {
  id: "computers_it",
  label: "Computers & IT Equipment",
  description: "Computers,  software, laptops, networking equipment, accessories, and IT hardware.",
  categories: [
    "Laptops & Notebooks",
    "Desktop Computers",
    "All-in-One Computers",
    "Mini PCs",
    "Computer Monitors",
    "Servers & Server Hardware",
    "Tablets & Accessories",
    "Keyboards & Mice",
    "Webcams & Computer Cameras",
    "Headsets & Computer Audio",
    "Speakers & Audio Accessories",
    "Printers",
    "Scanners",
    "Photocopiers & Multifunction Devices",
    "Projectors & Presentation Equipment",
    "Computer Cables & Adapters",
    "USB Hubs & Docking Stations",
    "Chargers & Power Adapters",
    "UPS & Backup Power",
    "Surge Protectors & Power Strips",
    "Hard Drives & SSDs",
    "USB Flash Drives",
    "Memory Cards & Card Readers",
    "RAM & Computer Memory",
    "Computer Processors & CPUs",
    "Motherboards",
    "Graphics Cards",
    "Computer Cases & Chassis",
    "Power Supply Units",
    "Cooling Fans & CPU Coolers",
    "Computer Components & Spare Parts",
    "Networking Equipment",
    "Routers & Wi-Fi Devices",
    "Network Switches",
    "Access Points & Wi-Fi Extenders",
    "Modems & Internet Devices",
    "Network Cables & Connectors",
    "Network Racks & Accessories",
    "CCTV & Surveillance Equipment",
    "Biometric & Access Control Devices",
    "POS Hardware",
    "Barcode Scanners & Readers",
    "Receipt Printers",
    "POS Terminals & Accessories",
    "Computer Speakers & Microphones",
    "Laptop Bags & Backpacks",
    "Laptop Stands & Cooling Pads",
    "Computer Desks & Accessories",
    "Software & Licenses",
    "Operating Systems & Utilities",
    "Antivirus & Security Software",
    "IT Tools & Maintenance Equipment",
    "Cleaning & Maintenance Supplies",
    "Others"
  ],
  unitOptions: [
    "pc",
    "unit",
    "piece",
    "set",
    "pair",
    "pack",
    "box",
    "carton",
    "bundle",
    "kit",
    "roll",
    "meter",
    "length"
  ],
  pluralMap: {
    pc: "Pcs",
    unit: "Units",
    piece: "Pieces",
    set: "Sets",
    pair: "Pairs",
    pack: "Packs",
    box: "Boxes",
    carton: "Cartons",
    bundle: "Bundles",
    kit: "Kits",
    roll: "Rolls",
    meter: "Meters",
    length: "Lengths"
  }
},

appliance: {
  id: "appliance",
  label: "Home & Office Appliance",
  description: "Home, kitchen, office, entertainment, cooling, cleaning, and electrical appliances.",
  categories: [
    "Refrigerators & Freezers",
    "Televisions & Smart TVs",
    "Home Theatre & Audio Systems",
    "Washing Machines & Dryers",
    "Air Conditioners",
    "Fans & Air Coolers",
    "Microwaves & Ovens",
    "Cookers & Gas Burners",
    "Electric Cookers & Hot Plates",
    "Blenders, Mixers & Grinders",
    "Kettles & Coffee Makers",
    "Toasters & Sandwich Makers",
    "Air Fryers & Deep Fryers",
    "Rice Cookers & Food Warmers",
    "Pressure Cookers",
    "Water Dispensers & Purifiers",
    "Water Heaters",
    "Vacuum Cleaners",
    "Irons & Garment Care",
    "Sewing Machines",
    "Office Printers & Scanners",
    "Photocopiers & Office Machines",
    "Computers & Monitors",
    "UPS & Inverter Systems",
    "Generators & Power Supplies",
    "Voltage Regulators & Stabilizers",
    "Extension Cords & Power Strips",
    "Lighting & Rechargeable Lamps",
    "Electric Fans & Accessories",
    "Kitchen Appliance Accessories",
    "TV & Audio Accessories",
    "Appliance Spare Parts",
    "Remote Controls",
    "Cables, Chargers & Adapters",
    "Cleaning & Maintenance Supplies",
    "Others"
  ],
  unitOptions: [
    "pc",
    "unit",
    "set",
    "pair",
    "pack",
    "carton",
    "box",
    "bundle",
    "kit"
  ],
  pluralMap: {
    pc: "Pcs",
    unit: "Units",
    set: "Sets",
    pair: "Pairs",
    pack: "Packs",
    carton: "Cartons",
    box: "Boxes",
    bundle: "Bundles",
    kit: "Kits"
  }
},

fashion_women: {
  id: "fashion_women",
  label: "Fashion (Women)",
  description: "Women's clothing, footwear, handbags, jewelry, fabrics, beauty accessories, and fashion essentials.",
  categories: [
    "Dresses & Gowns",
    "Tops, Blouses & Shirts",
    "Skirts",
    "Trousers & Pants",
    "Jeans",
    "Shorts",
    "Jumpsuits & Rompers",
    "Suits & Formal Wear",
    "Blazers & Jackets",
    "Native & Traditional Wear",
    "Asoebi & Occasion Wear",
    "Kaftans & Boubous",
    "Underwear & Lingerie",
    "Bras & Panties",
    "Sleepwear & Loungewear",
    "Activewear & Sportswear",
    "Maternity Wear",
    "Swimwear",
    "Women's Footwear",
    "Heels & Court Shoes",
    "Sandals & Slippers",
    "Sneakers & Trainers",
    "Handbags & Purses",
    "Clutches & Evening Bags",
    "Backpacks & Fashion Bags",
    "Belts & Waist Accessories",
    "Scarves & Shawls",
    "Headwear & Hats",
    "Wigs, Hair Extensions & Hair Accessories",
    "Jewelry",
    "Necklaces & Pendants",
    "Earrings",
    "Bracelets & Bangles",
    "Rings",
    "Watches",
    "Sunglasses & Eyewear",
    "Fashion Accessories",
    "Fabrics & Materials",
    "Sewing & Dressmaking Accessories",
    "Beauty & Makeup Accessories",
    "Others"
  ],
  unitOptions: [
    "pc",
    "pair",
    "set",
    "yard",
    "meter",
    "pack",
    "bundle",
    "box",
    "roll",
    "dozen",
    "carton"
  ],
  pluralMap: {
    pc: "Pcs",
    pair: "Pairs",
    set: "Sets",
    yard: "Yards",
    meter: "Meters",
    pack: "Packs",
    bundle: "Bundles",
    box: "Boxes",
    roll: "Rolls",
    dozen: "Dozens",
    carton: "Cartons"
  }
},

fashion_men: {
  id: "fashion_men",
  label: "Fashion (Men)",
  description: "Men's clothing, traditional wear, footwear, suits, accessories, and fashion essentials.",
  categories: [
    "Shirts & T-Shirts",
    "Polo Shirts",
    "Trousers & Pants",
    "Jeans",
    "Shorts",
    "Suits & Formal Wear",
    "Blazers & Jackets",
    "Native & Traditional Wear",
    "Agbada & Senator Wear",
    "Kaftans & Boubous",
    "Underwear",
    "Socks",
    "Sleepwear & Loungewear",
    "Sportswear & Activewear",
    "Casual Wear",
    "Men's Footwear",
    "Formal Shoes",
    "Sandals & Slippers",
    "Sneakers & Trainers",
    "Boots",
    "Belts",
    "Ties & Bow Ties",
    "Cufflinks & Tie Accessories",
    "Caps & Hats",
    "Traditional Caps",
    "Watches",
    "Wallets & Card Holders",
    "Bags & Backpacks",
    "Sunglasses & Eyewear",
    "Jewelry & Men's Accessories",
    "Fabrics & Materials",
    "Sewing & Dressmaking Accessories",
    "Others"
  ],
  unitOptions: [
    "pc",
    "pair",
    "set",
    "yard",
    "meter",
    "pack",
    "bundle",
    "box",
    "roll",
    "dozen",
    "carton"
  ],
  pluralMap: {
    pc: "Pcs",
    pair: "Pairs",
    set: "Sets",
    yard: "Yards",
    meter: "Meters",
    pack: "Packs",
    bundle: "Bundles",
    box: "Boxes",
    roll: "Rolls",
    dozen: "Dozens",
    carton: "Cartons"
  }
},

drinks_beverages: {
  id: "drinks_beverages",
  label: "Drinks, Wine & Liquor",
  description: "Alcoholic and non-alcoholic drinks, wines, spirits, beers, juices, and beverage supplies.",
  categories: [
    "Bottled & Sachet Water",
    "Soft Drinks & Sodas",
    "Carbonated Drinks",
    "Malt Drinks",
    "Energy Drinks",
    "Sports & Electrolyte Drinks",
    "Fruit Juices & Drinks",
    "Squashes & Concentrates",
    "Yoghurt & Dairy Drinks",
    "Tea, Coffee & Cocoa Drinks",
    "Herbal & Traditional Drinks",
    "Zobo & Hibiscus Drinks",
    "Kunu & Grain-Based Drinks",
    "Tigernut & Wellness Drinks",
    "Non-Alcoholic Sparkling Drinks",
    "Non-Alcoholic Malt & Specialty Drinks",
    "Beer & Lager",
    "Stout & Dark Beer",
    "Cider & Flavoured Alcoholic Drinks",
    "Wine",
    "Red Wine",
    "White Wine",
    "Rosé Wine",
    "Sparkling Wine & Champagne",
    "Fortified & Dessert Wine",
    "Champagne & Sparkling Drinks",
    "Brandy & Cognac",
    "Whisky & Bourbon",
    "Vodka",
    "Gin",
    "Rum",
    "Tequila",
    "Liqueurs & Cream Liqueurs",
    "Bitters & Herbal Spirits",
    "Cocktail & Beverage Mixers",
    "Tonic Water & Soda Water",
    "Drink Syrups & Concentrates",
    "Instant Beverage Powders",
    "Ice & Chilled Drinks",
    "Drinking Cups & Disposable Cups",
    "Straws & Beverage Accessories",
    "Flasks & Reusable Bottles",
    "Coolers & Ice Boxes",
    "Bottle Openers & Corkscrews",
    "Beverage Crates & Carriers",
    "Gift Packs & Beverage Hampers",
    "Others"
  ],
  unitOptions: [
    "pc",
    "unit",
    "bottle",
    "can",
    "sachet",
    "pack",
    "packet",
    "carton",
    "crate",
    "case",
    "box",
    "bundle",
    "bag",
    "jar",
    "tin",
    "litre",
    "ml",
    "dozen"
  ],
  pluralMap: {
    pc: "Pcs",
    unit: "Units",
    bottle: "Bottles",
    can: "Cans",
    sachet: "Sachets",
    pack: "Packs",
    packet: "Packets",
    carton: "Cartons",
    crate: "Crates",
    case: "Cases",
    box: "Boxes",
    bundle: "Bundles",
    bag: "Bags",
    jar: "Jars",
    tin: "Tins",
    litre: "Litres",
    ml: "ml",
    dozen: "Dozens"
  }
},

cosmetics_beauty_bodycare: {
  id: "cosmetics_beauty_bodycare",
  label: "Cosmetics, Beauty & Body Care",
  description: "Makeup, skincare, haircare, fragrances, body care, beauty tools, personal grooming products, and salon supplies.",
  categories: [
    "Face Makeup",
    "Foundation & Concealer",
    "Powder & Setting Products",
    "Blush, Bronzer & Highlighter",
    "Eye Makeup",
    "Eyeliners & Eye Pencils",
    "Mascara & Eye Products",
    "Eyeshadow & Palettes",
    "Lipsticks & Lip Products",
    "Lip Gloss & Lip Liners",
    "Makeup Brushes & Applicators",
    "Makeup Sponges & Tools",
    "Makeup Removers & Cleansers",
    "Skincare Products",
    "Face Cleansers & Toners",
    "Moisturizers & Face Creams",
    "Serums & Treatments",
    "Face Masks & Scrubs",
    "Sunscreen & Sun Care",
    "Acne & Blemish Care",
    "Body Lotions & Creams",
    "Body Oils & Butters",
    "Body Wash & Shower Gel",
    "Bath Soaps & Cleansers",
    "Body Scrubs & Exfoliants",
    "Deodorants & Antiperspirants",
    "Perfumes & Fragrances",
    "Body Sprays & Mists",
    "Hair Care Products",
    "Shampoo & Conditioner",
    "Hair Creams & Moisturizers",
    "Hair Oils & Treatments",
    "Hair Relaxers & Texturizers",
    "Hair Color & Dyes",
    "Hair Styling Products",
    "Wigs & Hair Extensions",
    "Braiding Hair & Attachments",
    "Hair Accessories",
    "Combs, Brushes & Detangling Tools",
    "Nail Care Products",
    "Nail Polish & Nail Treatments",
    "False Nails & Nail Accessories",
    "Manicure & Pedicure Tools",
    "Shaving & Grooming Products",
    "Razors & Shaving Accessories",
    "Beard Care Products",
    "Men's Grooming Products",
    "Feminine Care & Hygiene",
    "Oral Care & Breath Fresheners",
    "Beauty Devices & Electrical Tools",
    "Hair Dryers & Hair Styling Tools",
    "Hair Clippers & Trimmers",
    "Curling & Straightening Tools",
    "Salon Equipment & Accessories",
    "Beauty Packaging & Accessories",
    "Others"
  ],
  unitOptions: [
    "pc",
    "unit",
    "piece",
    "pair",
    "set",
    "pack",
    "box",
    "carton",
    "bundle",
    "kit",
    "bottle",
    "jar",
    "tube",
    "tin",
    "sachet",
    "roll",
    "dozen"
  ],
  pluralMap: {
    pc: "Pcs",
    unit: "Units",
    piece: "Pieces",
    pair: "Pairs",
    set: "Sets",
    pack: "Packs",
    box: "Boxes",
    carton: "Cartons",
    bundle: "Bundles",
    kit: "Kits",
    bottle: "Bottles",
    jar: "Jars",
    tube: "Tubes",
    tin: "Tins",
    sachet: "Sachets",
    roll: "Rolls",
    dozen: "Dozens"
  }
},

babies_childcare: {
  id: "babies_childcare",
  label: "Babies & Childcare",
  description: "Baby clothing, nursery essentials, childcare products, toys, and children's daily needs.",
  categories: [
    "Baby Clothing",
    "Baby Bodysuits & Rompers",
    "Baby Sleepsuits & Sleepwear",
    "Baby Dresses & Outfits",
    "Baby Shoes & Socks",
    "Baby Caps & Headwear",
    "Baby Bibs & Burp Cloths",
    "Baby Underwear",
    "Children's Clothing",
    "Children's Footwear",
    "Children's Bags & Backpacks",
    "Diapers & Nappies",
    "Baby Wipes",
    "Baby Changing Mats & Accessories",
    "Baby Bath & Toiletries",
    "Baby Soap & Body Wash",
    "Baby Shampoo & Hair Care",
    "Baby Lotion & Skin Care",
    "Baby Powder & Hygiene Products",
    "Baby Feeding Bottles",
    "Bottle Nipples & Accessories",
    "Breastfeeding & Nursing Accessories",
    "Baby Formula & Infant Nutrition",
    "Baby Food & Cereals",
    "Baby Feeding Utensils",
    "Baby Cups & Sippy Cups",
    "High Chairs & Booster Seats",
    "Baby Carriers & Slings",
    "Baby Strollers & Prams",
    "Baby Car Seats",
    "Baby Cots & Cribs",
    "Nursery Furniture",
    "Baby Bedding & Blankets",
    "Mosquito Nets & Nursery Nets",
    "Baby Towels & Washcloths",
    "Pacifiers & Teething Products",
    "Baby Monitors",
    "Child Safety Products",
    "Potty Training Products",
    "Children's Toys & Games",
    "Educational Toys",
    "Ride-On & Outdoor Toys",
    "School & Learning Supplies",
    "Children's Hair Accessories",
    "Children's Personal Care",
    "Maternity & Nursing Wear",
    "Others"
  ],
  unitOptions: [
    "pc",
    "unit",
    "piece",
    "pair",
    "set",
    "pack",
    "packet",
    "box",
    "carton",
    "bundle",
    "dozen",
    "bottle",
    "tin",
    "jar",
    "can",
    "sachet",
    "tube"
  ],
  pluralMap: {
    pc: "Pcs",
    unit: "Units",
    piece: "Pieces",
    pair: "Pairs",
    set: "Sets",
    pack: "Packs",
    packet: "Packets",
    box: "Boxes",
    carton: "Cartons",
    bundle: "Bundles",
    dozen: "Dozens",
    bottle: "Bottles",
    tin: "Tins",
    jar: "Jars",
    can: "Cans",
    sachet: "Sachets",
    tube: "Tubes"
  }
},

jewelry_luxury: {
  id: "jewelry_luxury",
  label: "Jewelry & Luxury Accessories",
  description: "Fashion jewelry, luxury accessories, watches, eyewear, bags, and related items.",
  categories: [
    "Necklaces & Pendants",
    "Chains",
    "Earrings",
    "Stud Earrings",
    "Hoop & Drop Earrings",
    "Bracelets & Bangles",
    "Anklets",
    "Rings",
    "Engagement & Wedding Rings",
    "Brooches & Pins",
    "Jewelry Sets",
    "Body Jewelry",
    "Cufflinks",
    "Tie Clips & Tie Accessories",
    "Watches",
    "Smart Watches",
    "Watch Straps & Bands",
    "Watch Accessories",
    "Sunglasses & Eyewear",
    "Eyeglasses & Frames",
    "Luxury Handbags",
    "Clutches & Evening Bags",
    "Wallets & Card Holders",
    "Belts & Designer Accessories",
    "Scarves & Fashion Accessories",
    "Hair Jewelry & Accessories",
    "Bridal Jewelry",
    "Traditional & Cultural Jewelry",
    "Beaded Jewelry",
    "Pearls & Pearl Jewelry",
    "Gold Jewelry",
    "Silver Jewelry",
    "Gemstone Jewelry",
    "Diamond Jewelry",
    "Costume & Fashion Jewelry",
    "Jewelry Findings & Components",
    "Jewelry Chains & Clasps",
    "Jewelry Boxes & Organizers",
    "Watch Boxes & Cases",
    "Gift Boxes & Luxury Packaging",
    "Jewelry Cleaning & Care",
    "Watch Cleaning & Care",
    "Jewelry Display Equipment",
    "Luxury Gift Items",
    "Others"
  ],
  unitOptions: [
    "pc",
    "piece",
    "pair",
    "set",
    "pack",
    "box",
    "carton",
    "bundle",
    "dozen",
    "kit"
  ],
  pluralMap: {
    pc: "Pcs",
    piece: "Pieces",
    pair: "Pairs",
    set: "Sets",
    pack: "Packs",
    box: "Boxes",
    carton: "Cartons",
    bundle: "Bundles",
    dozen: "Dozens",
    kit: "Kits"
  }
},

fabrics_textiles: {
  id: "fabrics_textiles",
  label: "Fabrics & Textiles",
  description: "Fashion fabrics, traditional textiles, lace, Ankara, wrappers, sewing materials, and textile accessories.",
  categories: [
    "Ankara & African Prints",
    "Lace Fabrics",
    "French Lace",
    "Swiss Lace",
    "English Lace",
    "Guipure & Cord Lace",
    "Atiku & Senator Fabrics",
    "Cashmere & Wool Fabrics",
    "Cotton Fabrics",
    "Linen Fabrics",
    "Silk & Satin Fabrics",
    "Chiffon Fabrics",
    "Velvet Fabrics",
    "Denim Fabrics",
    "Jersey & Stretch Fabrics",
    "Polyester Fabrics",
    "Nylon & Synthetic Fabrics",
    "Crepe Fabrics",
    "Organza & Tulle",
    "Net & Mesh Fabrics",
    "Kente & Woven Fabrics",
    "Traditional Nigerian Textiles",
    "Aso Oke",
    "George & Wrapper Fabrics",
    "Adire & Tie-Dye",
    "Brocade & Damask",
    "Children's Fabrics",
    "School Uniform Fabrics",
    "Upholstery Fabrics",
    "Curtain & Drapery Fabrics",
    "Bedsheet & Bedding Fabrics",
    "Towels & Terry Textiles",
    "Blankets & Throws",
    "Ready-Made Wrappers",
    "Head Tie & Gele Fabrics",
    "Sewing Threads",
    "Embroidery Threads",
    "Zippers",
    "Buttons & Fasteners",
    "Elastic Bands",
    "Bias Tape & Binding",
    "Interfacing & Linings",
    "Sewing Needles & Pins",
    "Embroidery & Decorative Materials",
    "Beads, Stones & Appliques",
    "Ribbons & Trimmings",
    "Fabric Adhesives",
    "Tailoring Accessories",
    "Others"
  ],
  unitOptions: [
    "yard",
    "meter",
    "piece",
    "pc",
    "roll",
    "bundle",
    "pack",
    "box",
    "set",
    "pair",
    "dozen",
    "cone",
    "spool"
  ],
  pluralMap: {
    yard: "Yards",
    meter: "Meters",
    piece: "Pieces",
    pc: "Pcs",
    roll: "Rolls",
    bundle: "Bundles",
    pack: "Packs",
    box: "Boxes",
    set: "Sets",
    pair: "Pairs",
    dozen: "Dozens",
    cone: "Cones",
    spool: "Spools"
  }
},

footwear_leather: {
  id: "footwear_leather",
  label: "Footwear",
  description: "Shoes, sandals, slippers, boots, leather products, safety boots, footwear accessories.",
  categories: [
    "Men's Shoes",
    "Women's Shoes",
    "Children's Shoes",
    "Formal Shoes",
    "Casual Shoes",
    "Sneakers & Trainers",
    "Sports Shoes",
    "Boots",
    "Safety Boots & Work Shoes",
    "Sandals",
    "Slippers & Slides",
    "Heels & Court Shoes",
    "Flats & Loafers",
    "School Shoes",
    "Traditional & Native Footwear",
    "Orthopedic & Comfort Footwear",
    "Rain Boots & Outdoor Footwear",
    "Leather Shoes",
    "Leather Sandals",
    "Leather Slippers",
    "Leather Bags",
    "Handbags & Purses",
    "Wallets & Card Holders",
    "Belts",
    "Leather Briefcases & Laptop Bags",
    "Travel & Luggage Bags",
    "Backpacks",
    "Travel Bags & Suitcases",
    "Leather Pouches & Accessories",
    "Shoe Care Products",
    "Shoe Polish & Cream",
    "Shoe Brushes & Cleaning Tools",
    "Shoe Laces",
    "Insoles & Foot Supports",
    "Shoe Soles & Heels",
    "Buckles & Shoe Accessories",
    "Leather Materials",
    "Leather Hides & Skins",
    "Synthetic Leather & Leatherette",
    "Shoe-Making Materials",
    "Shoe-Making Tools",
    "Shoe Adhesives & Glues",
    "Leather Dyes & Finishes",
    "Sewing Threads & Needles",
    "Leather Hardware & Fasteners",
    "Footwear Packaging",
    "Others"
  ],
  unitOptions: [
    "pc",
    "pair",
    "piece",
    "set",
    "pack",
    "box",
    "carton",
    "bundle",
    "dozen",
    "meter",
    "yard",
    "roll",
    "sheet"
  ],
  pluralMap: {
    pc: "Pcs",
    pair: "Pairs",
    piece: "Pieces",
    set: "Sets",
    pack: "Packs",
    box: "Boxes",
    carton: "Cartons",
    bundle: "Bundles",
    dozen: "Dozens",
    meter: "Meters",
    yard: "Yards",
    roll: "Rolls",
    sheet: "Sheets"
  }
},

sporting_goods_fitness: {
  id: "sporting_goods_fitness",
  label: "Sporting Goods & Fitness",
  description: "Sports equipment, fitness gear, exercise accessories, outdoor recreation products, and sporting apparel.",
  categories: [
    "Football Equipment",
    "Football Boots & Cleats",
    "Football Jerseys & Kits",
    "Football Balls",
    "Goal Posts & Nets",
    "Shin Guards & Protective Gear",
    "Basketball Equipment",
    "Basketballs",
    "Basketball Hoops & Nets",
    "Basketball Jerseys & Accessories",
    "Tennis Equipment",
    "Tennis Rackets",
    "Tennis Balls",
    "Tennis Nets & Accessories",
    "Table Tennis Equipment",
    "Table Tennis Bats & Balls",
    "Table Tennis Tables & Nets",
    "Badminton Equipment",
    "Badminton Rackets & Shuttlecocks",
    "Volleyball Equipment",
    "Volleyballs & Nets",
    "Boxing & Combat Sports Equipment",
    "Boxing Gloves & Hand Wraps",
    "Punching Bags",
    "Protective Sports Gear",
    "Running & Athletics Equipment",
    "Running Shoes",
    "Athletic Clothing",
    "Fitness & Gym Equipment",
    "Dumbbells & Hand Weights",
    "Barbells & Weight Plates",
    "Kettlebells",
    "Resistance Bands",
    "Exercise Mats",
    "Yoga & Pilates Equipment",
    "Skipping Ropes",
    "Exercise Benches",
    "Home Gym Equipment",
    "Treadmills & Cardio Machines",
    "Stationary Bikes",
    "Elliptical & Cross Trainers",
    "Gym Machines & Equipment",
    "Weightlifting Accessories",
    "Gym Gloves & Supports",
    "Sports Bags & Backpacks",
    "Sports Bottles & Hydration Gear",
    "Sports Towels & Accessories",
    "Swimming Equipment",
    "Swimming Goggles & Caps",
    "Swimming Accessories",
    "Cycling Equipment",
    "Bicycles",
    "Bicycle Parts & Accessories",
    "Cycling Helmets & Protective Gear",
    "Outdoor & Camping Equipment",
    "Hiking & Trekking Equipment",
    "Sports Watches & Fitness Trackers",
    "Fitness Accessories",
    "Sports Protective Equipment",
    "Sports Training Equipment",
    "Sports Cones & Training Markers",
    "Medals, Trophies & Awards",
    "Sports Apparel",
    "Sports Socks & Accessories",
    "Others"
  ],
  unitOptions: [
    "pc",
    "piece",
    "pair",
    "set",
    "pack",
    "box",
    "carton",
    "bundle",
    "kit",
    "unit",
    "dozen"
  ],
  pluralMap: {
    pc: "Pcs",
    piece: "Pieces",
    pair: "Pairs",
    set: "Sets",
    pack: "Packs",
    box: "Boxes",
    carton: "Cartons",
    bundle: "Bundles",
    kit: "Kits",
    unit: "Units",
    dozen: "Dozens"
  }
},

stationery_office: {
  id: "stationery_office",
  label: "Stationery & Office Supplies",
  description: "Writing materials, school supplies, office stationery, paper products and office essentials.",
  categories: [
    "Writing Pens & Ballpoint Pens",
    "Pencils & Mechanical Pencils",
    "Markers & Highlighters",
    "Correction Supplies",
    "Erasers & Sharpeners",
    "Notebooks & Exercise Books",
    "Writing Pads & Memo Pads",
    "Diaries & Planners",
    "Paper & Printing Paper",
    "Specialty & Colored Paper",
    "Cardstock & Bristol Board",
    "Envelopes",
    "Files & Folders",
    "Ring Binders & Lever Arch Files",
    "Document Wallets & Organizers",
    "Clipboards",
    "Staplers & Staples",
    "Paper Clips & Binder Clips",
    "Pins, Tacks & Drawing Pins",
    "Rubber Bands",
    "Glue & Adhesives",
    "Scissors & Cutters",
    "Rulers & Measuring Tools",
    "Geometry & Mathematical Instruments",
    "School Bags & Backpacks",
    "Lunch Boxes & School Accessories",
    "Art & Drawing Supplies",
    "Craft & Hobby Materials",
    "Whiteboards & Notice Boards",
    "Whiteboard Markers & Accessories",
    "Office Desk Accessories",
    "Desk Organizers & Trays",
    "Calendars & Office Planners",
    "Printing Inks & Toners",
    "Printer Ribbons & Consumables",
    "Labels & Labeling Supplies",
    "Receipt & POS Paper",
    "Calculators",
    "Shredders & Document Disposal",
    "Packaging & Mailing Supplies",
    "Office Forms & Business Books",
    "Registers & Record Books",
    "School & Examination Supplies",
    "Others"
  ],
  unitOptions: [
    "pc",
    "piece",
    "pack",
    "box",
    "ream",
    "book",
    "dozen",
    "set",
    "pair",
    "bundle",
    "roll",
    "carton",
    "sheet",
    "pad"
  ],
  pluralMap: {
    pc: "Pcs",
    piece: "Pieces",
    pack: "Packs",
    box: "Boxes",
    ream: "Reams",
    book: "Books",
    dozen: "Dozens",
    set: "Sets",
    pair: "Pairs",
    bundle: "Bundles",
    roll: "Rolls",
    carton: "Cartons",
    sheet: "Sheets",
    pad: "Pads"
  }
},

electrical: {
  id: "electrical",
  label: "Electrical",
  description: "Electrical equipment, cables, lighting, solar equipment, installation materials, and accessories.",
  categories: [
    "Cables & Wires",
    "Cable Accessories",
    "Switches & Sockets",
    "Plugs & Adapters",
    "Lighting & Bulbs",
    "Lighting Fixtures",
    "LED Lighting",
    "Outdoor & Security Lighting",
    "Circuit Breakers",
    "Distribution Boards & Consumer Units",
    "Fuses & Fuse Holders",
    "Surge Protection & Voltage Protection",
    "Changeover Switches",
    "Contactors & Relays",
    "Timers & Control Devices",
    "Conduit Pipes & Fittings",
    "Trunking & Cable Management",
    "Junction Boxes & Enclosures",
    "Electrical Tapes & Insulation Materials",
    "Cable Glands & Terminals",
    "Lugs, Ferrules & Connectors",
    "Earthing & Lightning Protection",
    "Meters & Measuring Instruments",
    "Electrical Installation Tools",
    "Hand Tools",
    "Industrial Electricals",
    "Motors & Motor Accessories",
    "Generators & Generator Accessories",
    "Solar Panels & Accessories",
    "Solar Inverters",
    "Inverter Batteries",
    "Solar Protection & Distribution",
    "Batteries & Chargers",
    "Extension Boxes & Extension Cords",
    "Plugs, Sockets & Power Strips",
    "Fans & Ventilation",
    "Doorbells & Intercoms",
    "Security & Access Devices",
    "Electrical Heating Appliances",
    "Transformers & Power Supplies",
    "Wiring Accessories",
    "Installation Hardware & Fasteners",
    "Electrical Consumables",
    "Others"
  ],
  unitOptions: [
    "pc",
    "coil",
    "roll",
    "length",
    "meter",
    "pack",
    "box",
    "carton",
    "set",
    "pair",
    "bundle",
    "kit",
    "bag",
    "ream"
  ],
  pluralMap: {
    pc: "Pcs",
    coil: "Coils",
    roll: "Rolls",
    length: "Lengths",
    meter: "Meters",
    pack: "Packs",
    box: "Boxes",
    carton: "Cartons",
    set: "Sets",
    pair: "Pairs",
    bundle: "Bundles",
    kit: "Kits",
    bag: "Bags",
    ream: "Reams"
  }
},

building_materials: {
  id: "building_materials",
  label: "Building Materials",
  description: "Cement, blocks, roofing materials, rods & metals, tiles, doors, windows, and construction supplies.",
  categories: [
    "Cement & Binders",
    "Blocks, Bricks & Pavers",
    "Sand, Gravel & Aggregates",
    "Reinforcement Rods & Steel",
    "Binding Wire & Reinforcement Accessories",
    "Roofing Sheets",
    "Roofing Tiles",
    "Roofing Timber & Accessories",
    "Roofing Nails & Fasteners",
    "Roofing Insulation & Underlay",
    "Ceiling Materials",
    "Ceiling Boards & Panels",
    "Ceiling Profiles & Accessories",
    "Doors & Door Frames",
    "Windows & Window Frames",
    "Glass & Glazing Materials",
    "Tiles & Tiling Materials",
    "Floor Tiles",
    "Wall Tiles",
    "Tile Adhesives & Grout",
    "Paints & Coatings",
    "Primers & Undercoats",
    "Paint Thinners & Solvents",
    "Wall Fillers & Plasters",
    "Plasterboard & Drywall",
    "Waterproofing Materials",
    "Building Chemicals & Additives",
    "Mortar & Concrete Additives",
    "Timber & Wood Products",
    "Plywood & Boards",
    "Formwork Materials",
    "Scaffolding & Construction Supports",
    "Plumbing & Drainage Materials",
    "Electrical Building Materials",
    "Insulation Materials",
	"Rods & Metals",
	"Aluminium Products",
    "Adhesives, Sealants & Caulking",
    "Nails, Screws & Fasteners",
    "Locks, Hinges & Door Hardware",
    "Sanitary & Bathroom Fixtures",
    "Kitchen & Building Fixtures",
    "Construction Safety Materials",
    "General Construction Supplies",
    "Others"
  ],
  unitOptions: [
    "pc",
    "piece",
    "bag",
    "kg",
    "g",
    "ton",
    "length",
    "meter",
    "yard",
    "sheet",
    "roll",
    "bundle",
    "pack",
    "box",
    "carton",
    "set",
    "pair",
    "bucket",
    "tin",
    "drum",
    "load"
  ],
  pluralMap: {
    pc: "Pcs",
    piece: "Pieces",
    bag: "Bags",
    kg: "Kg",
    g: "g",
    ton: "Tons",
    length: "Lengths",
    meter: "Meters",
    yard: "Yards",
    sheet: "Sheets",
    roll: "Rolls",
    bundle: "Bundles",
    pack: "Packs",
    box: "Boxes",
    carton: "Cartons",
    set: "Sets",
    pair: "Pairs",
    bucket: "Buckets",
    tin: "Tins",
    drum: "Drums",
    load: "Loads"
  }
},

plumbing: {
  id: "plumbing",
  label: "Plumbing & Accessories",
  description: "Pipework, fittings, valves, pumps, bathroom & kitchen, plumbing installation materials.",
  categories: [
    "PVC Pipes",
    "PPR Pipes",
    "HDPE Pipes",
    "CPVC Pipes",
    "Galvanized Iron Pipes",
    "Flexible & Braided Hoses",
    "Drainage Pipes",
    "Pipe Fittings",
    "Elbows & Bends",
    "Tees & Cross Fittings",
    "Couplers & Sockets",
    "Reducers & Adaptors",
    "Unions & Nipples",
    "Pipe Caps & Plugs",
    "Pipe Clamps & Supports",
    "Valves & Taps",
    "Ball Valves",
    "Gate Valves",
    "Check Valves & Non-Return Valves",
    "Stop Cocks & Angle Valves",
    "Bib Taps & Water Taps",
    "Mixer Taps & Faucets",
    "Water Tanks",
    "Water Pumps",
    "Submersible Pumps",
    "Pressure Pumps & Booster Pumps",
    "Pump Accessories & Spare Parts",
    "Toilet & WC Fittings",
    "Wash Basins & Accessories",
    "Bathtubs & Shower Fittings",
    "Showers & Shower Accessories",
    "Bathroom Accessories",
    "Kitchen Sink & Accessories",
    "Floor Drains & Gullies",
    "Manholes & Drainage Covers",
    "Water Filters & Purifiers",
    "Water Heaters",
    "Pipe Sealants & Thread Tape",
    "Plumbing Adhesives & Solvents",
    "Rubber Washers & Gaskets",
    "Pipe Tools & Cutting Tools",
    "Sewer & Drainage Accessories",
    "Water Metering Accessories",
    "Plumbing Hardware & Fasteners",
    "Others"
  ],
  unitOptions: [
    "pc",
    "piece",
    "length",
    "meter",
    "roll",
    "coil",
    "set",
    "pair",
    "pack",
    "box",
    "carton",
    "bundle",
    "kit"
  ],
  pluralMap: {
    pc: "Pcs",
    piece: "Pieces",
    length: "Lengths",
    meter: "Meters",
    roll: "Rolls",
    coil: "Coils",
    set: "Sets",
    pair: "Pairs",
    pack: "Packs",
    box: "Boxes",
    carton: "Cartons",
    bundle: "Bundles",
    kit: "Kits"
  }
},

hardware_tools: {
  id: "hardware_tools",
  label: "Hardware & Technical Tools",
  description: "Hand tools, power tools, workshop equipment, safety equipment, and technical supplies.",
  categories: [
    "Hand Tools",
    "Hammers & Mallets",
    "Screwdrivers",
    "Pliers & Cutters",
    "Spanners & Wrenches",
    "Sockets & Ratchets",
    "Allen Keys & Hex Tools",
    "Drills & Drill Bits",
    "Power Drills & Impact Drivers",
    "Grinders & Cutting Tools",
    "Saws & Cutting Equipment",
    "Sanders & Polishing Tools",
    "Power Tool Accessories",
    "Measuring & Layout Tools",
    "Levels & Spirit Levels",
    "Tape Measures",
    "Electrical Testing Tools",
    "Workshop & Mechanical Tools",
    "Automotive Tools",
    "Welding Equipment & Accessories",
    "Air Compressors & Pneumatic Tools",
    "Generators & Workshop Power",
    "Nails, Screws & Fasteners",
    "Bolts, Nuts & Washers",
    "Anchors & Wall Plugs",
    "Hooks, Brackets & Mounting Hardware",
    "Locks, Padlocks & Security Hardware",
    "Hinges & Latches",
    "Chains, Ropes & Cables",
    "Adhesives & Sealants",
    "Lubricants & Maintenance Products",
    "Abrasives & Grinding Discs",
    "Cutting Blades & Saw Blades",
    "Paint & Decorating Tools",
    "Brushes, Rollers & Scrapers",
    "Ladders & Access Equipment",
    "Work Benches & Workshop Equipment",
    "Storage Boxes & Tool Cases",
    "Tool Bags & Belts",
    "Safety Equipment & PPE",
    "Gloves & Protective Wear",
    "Masks, Goggles & Face Protection",
    "Construction & Site Equipment",
    "Agricultural & Garden Tools",
    "General Hardware",
    "Others"
  ],
  unitOptions: [
    "pc",
    "piece",
    "pair",
    "set",
    "kit",
    "pack",
    "box",
    "carton",
    "bundle",
    "roll",
    "meter",
    "length",
    "kg",
    "g",
    "litre",
    "ml"
  ],
  pluralMap: {
    pc: "Pcs",
    piece: "Pieces",
    pair: "Pairs",
    set: "Sets",
    kit: "Kits",
    pack: "Packs",
    box: "Boxes",
    carton: "Cartons",
    bundle: "Bundles",
    roll: "Rolls",
    meter: "Meters",
    length: "Lengths",
    kg: "Kg",
    g: "g",
    litre: "Litres",
    ml: "ml"
  }
},

automotive_parts: {
  id: "automotive_parts",
  label: "Automotive Parts & Accessories",
  description: "Vehicle spare parts, maintenance products, tools, tyres, accessories, automotive supplies.",
  categories: [
    "Engine Parts",
    "Engine Filters",
    "Oil & Fuel Filters",
    "Air Filters",
    "Spark Plugs & Ignition Parts",
    "Belts & Tensioners",
    "Gaskets & Seals",
    "Engine Mounts",
    "Cooling System Parts",
    "Radiators & Radiator Accessories",
    "Water Pumps",
    "Thermostats",
    "Cooling Fans & Motors",
    "Hoses & Pipes",
    "Fuel System Parts",
    "Fuel Pumps",
    "Fuel Injectors",
    "Carburetors & Components",
    "Fuel Tanks & Accessories",
    "Transmission & Gearbox Parts",
    "Clutch Parts",
    "Clutch Plates & Kits",
    "Gearbox Mounts & Components",
    "Drivetrain & Differential Parts",
    "Suspension Parts",
    "Shock Absorbers",
    "Struts & Coil Springs",
    "Control Arms & Bushings",
    "Ball Joints & Tie Rods",
    "Wheel Bearings & Hubs",
    "Steering Parts",
    "Brake System Parts",
    "Brake Pads & Shoes",
    "Brake Discs & Drums",
    "Brake Calipers & Components",
    "Brake Hoses & Lines",
    "Electrical & Electronic Parts",
    "Batteries & Battery Accessories",
    "Alternators & Starters",
    "Sensors & Switches",
    "Relays & Fuses",
    "Vehicle Lighting",
    "Headlights & Headlamp Parts",
    "Tail Lights & Brake Lights",
    "Indicators & Fog Lights",
    "Bulbs & LED Vehicle Lighting",
    "Wiper Blades & Washers",
    "Vehicle Horns",
    "Air Conditioning Parts",
    "AC Compressors & Components",
    "AC Filters & Refrigerant Accessories",
    "Tyres & Tubes",
    "Wheel Rims & Accessories",
    "Wheel Nuts & Bolts",
    "Interior Accessories",
    "Car Seats & Covers",
    "Floor Mats & Carpets",
    "Steering Covers",
    "Dashboard Accessories",
    "Exterior Accessories",
    "Car Mirrors",
    "Mud Flaps & Guards",
    "Roof Racks & Carriers",
    "Tow Bars & Towing Accessories",
    "Car Audio & Entertainment",
    "Car Security & Alarm Systems",
    "Dash Cameras & Vehicle Cameras",
    "GPS & Tracking Accessories",
    "Car Chargers & Power Accessories",
    "Vehicle Cleaning Products",
    "Car Wash & Detailing Supplies",
    "Engine Oils & Lubricants",
    "Coolants & Brake Fluids",
    "Automotive Chemicals",
    "Garage & Workshop Tools",
    "Vehicle Diagnostic Tools",
    "Automotive Hardware & Fasteners",
    "Others"
  ],
  unitOptions: [
    "pc",
    "piece",
    "pair",
    "set",
    "kit",
    "pack",
    "box",
    "carton",
    "bundle",
    "bottle",
    "can",
    "litre",
    "ml",
    "kg",
    "g",
    "roll",
    "meter"
  ],
  pluralMap: {
    pc: "Pcs",
    piece: "Pieces",
    pair: "Pairs",
    set: "Sets",
    kit: "Kits",
    pack: "Packs",
    box: "Boxes",
    carton: "Cartons",
    bundle: "Bundles",
    bottle: "Bottles",
    can: "Cans",
    litre: "Litres",
    ml: "ml",
    kg: "Kg",
    g: "g",
    roll: "Rolls",
    meter: "Meters"
  }
},

agrochemicals_farm_inputs: {
  id: "agrochemicals_farm_inputs",
  label: "Agrochemicals & Farm Inputs",
  description: "Seeds, fertilizers, crop protection products, animal feeds, farm supplies, and agricultural  materials.",
  categories: [
    "Crop Seeds",
    "Vegetable Seeds",
    "Grain & Cereal Seeds",
    "Legume Seeds",
    "Root & Tuber Planting Materials",
    "Hybrid & Improved Seeds",
    "Seed Treatment Products",
    "Fertilizers",
    "NPK Fertilizers",
    "Urea & Nitrogen Fertilizers",
    "Phosphate & Potassium Fertilizers",
    "Organic Fertilizers",
    "Manure & Compost",
    "Foliar Fertilizers",
    "Micronutrients & Soil Amendments",
    "Lime & Soil Conditioners",
    "Herbicides",
    "Insecticides",
    "Fungicides",
    "Acaricides & Miticides",
    "Nemanticides",
    "Rodenticides",
    "Molluscicides",
    "Biological Crop Protection",
    "Pesticide Adjuvants",
    "Spraying & Application Products",
    "Knapsack Sprayers",
    "Motorized Sprayers",
    "Sprayer Pumps & Spare Parts",
    "Spray Nozzles & Accessories",
    "Protective Clothing & PPE",
    "Animal Feed",
    "Poultry Feed",
    "Fish Feed",
    "Pig Feed",
    "Cattle & Livestock Feed",
    "Feed Concentrates",
    "Feed Premixes",
    "Feed Additives",
    "Vitamins & Mineral Supplements",
    "Animal Health Products",
    "Veterinary Farm Supplies",
    "Livestock Breeding Supplies",
    "Poultry Farm Supplies",
    "Fish Farming Supplies",
    "Farm Irrigation Equipment",
    "Water Pumps & Farm Pumps",
    "Drip Irrigation Supplies",
    "Watering Equipment",
    "Greenhouse & Nursery Supplies",
    "Planting Trays & Seedling Materials",
    "Nursery Bags & Pots",
    "Mulching Materials",
    "Agricultural Nets & Covers",
    "Farm Tools & Implements",
    "Hoes, Cutlasses & Digging Tools",
    "Pruning & Harvesting Tools",
    "Wheelbarrows & Farm Carts",
    "Storage Bags & Sacks",
    "Harvesting & Post-Harvest Supplies",
    "Farm Twine, Rope & Binding Materials",
    "Agricultural Measuring Equipment",
    "Others"
  ],
  unitOptions: [
    "pc",
    "piece",
    "pair",
    "set",
    "pack",
    "packet",
    "bag",
    "sack",
    "bottle",
    "can",
    "tin",
    "jar",
    "carton",
    "box",
    "bundle",
    "kg",
    "g",
    "litre",
    "ml",
    "ton",
    "drum"
  ],
  pluralMap: {
    pc: "Pcs",
    piece: "Pieces",
    pair: "Pairs",
    set: "Sets",
    pack: "Packs",
    packet: "Packets",
    bag: "Bags",
    sack: "Sacks",
    bottle: "Bottles",
    can: "Cans",
    tin: "Tins",
    jar: "Jars",
    carton: "Cartons",
    box: "Boxes",
    bundle: "Bundles",
    kg: "Kg",
    g: "g",
    litre: "Litres",
    ml: "ml",
    ton: "Tons",
    drum: "Drums"
  }
}
};

export function getVerticalConfig(verticalKey?: string | null): VerticalConfig {
  if (verticalKey && RETAIL_VERTICALS[verticalKey]) {
    return RETAIL_VERTICALS[verticalKey];
  }
  return RETAIL_VERTICALS["grocery"];
}